require 'bootstrap'
require 'jquery-rails'
require 'simple_form'
require 'paperclip'
require 'active_link_to'
require 'font-awesome-rails'
require 'devise'
require 'devise_cas_authenticatable'
require 'cancancan'
require 'rails_admin'

require 'failuregem/rails/engine'
